[package]
name = "pongy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy-inspector-egui = "0.17"
rand = "0.8"
iyes_loopless = "0.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }


[profile.dev.package."*"]
opt-level = 3
